version: "3"
services:
  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    network_mode: "host"
    shm_size: 10g
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  nifi:
    image: apache/nifi:1.14.0
    network_mode: "host"
    ports:
      - 9000:9000
      - 8082:8082
      - 6342:6342
      - 11443:11443  
    environment:     
      - AUTH=ldap
      - KEYSTORE_PATH=/opt/nifi/nifi-current/provenance_repository/ssl/keystore.jks
      - KEYSTORE_TYPE=jks
      - KEYSTORE_PASSWORD=
      - TRUSTSTORE_PATH=/opt/nifi/nifi-current/provenance_repository/ssl/truststore.jks
      - TRUSTSTORE_PASSWORD=
      - TRUSTSTORE_TYPE=jks
      - INITIAL_ADMIN_IDENTITY=username
      - LDAP_AUTHENTICATION_STRATEGY=SIMPLE
      - LDAP_MANAGER_DN=cn=,ou=,ou=,ou=,ou=,dc=,dc=
      - LDAP_MANAGER_PASSWORD=
      - LDAP_USER_SEARCH_BASE=DC=,DC=
      - LDAP_USER_SEARCH_FILTER=sAMAccountName={0}
      - LDAP_IDENTITY_STRATEGY=USE_USERNAME
      - LDAP_URL=ldap://
      - NIFI_CLUSTER_PROTOCOL_IS_SECURE=false
      - NIFI_CLUSTER_IS_NODE=false
      - NIFI_SENSITIVE_PROPS_KEY=
      - NIFI_CLUSTER_ADDRESS=
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=
      - NIFI_WEB_HTTP_PORT=900
      - NIFI_ZK_CONNECT_STRING=
      - NIFI_ELECTION_MAX_WAIT=1 min
    volumes:
      - /mnt/sda/nifi/conf/:/opt/nifi/nifi-current/conf/
      - /mnt/sda/nifi/log/nifi/:/opt/nifi/nifi-current/logs/  
      - /mnt/sda/nifi/provenance_repository/:/opt/nifi/nifi-current/provenance_repository
      - /mnt/sda/nifi/content_repository/:/opt/nifi/nifi-current/content_repository/
      - /mnt/sda/nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository     
